import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/ui/organisms/Navbar/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="fixed top-0 z-50 mx-auto w-screen border-b border-gray-400 backdrop-blur">
					<Navbar />
				</header>
				<main className="mx-auto mt-20 max-w-2xl px-8 py-8 sm:px-6 lg:max-w-7xl">{children}</main>
			</body>
		</html>
	);
}
